### ISSUE TITLE
Automation rule s hľadaním výrazu v obsahu prílohy

### ISSUE THREAD

**Issue by luciajanikova** [slovensko-digital/govbox-pro#370]
Máme požiadavku na priadanie funkcionality od reálnych používateľov. Na základe obsahu prílohy (`MessageObject` alebo `NestedMessaegObject`) by malo byť možné automatizáciou pridať štítok na vlákno alebo upraviť názov vlákna.

Konkrétne pravidlá môžu vyzerať napr. nejako takto: 
- Ak sa v ktorejkoľvek prílohe správy vyskytuje reťazec "50881337", chcem aby názov daného vlákna bol upravený na "Služby Slovensko.Digital, s.r.o. - {pôvodný názov vlákna}"
- Ak sa v ktorejkoľvek prílohe správy vyskytuje reťazec "Služby Slovensko.Digital, s.r.o.", chcem aby na dané vlákno bol pridaný štítok "SSD"

!Pozor:
- Treba sa pozerať na všetky `MessageObjects` správy (prílohy, aj formulár), ak `MessageObject` nemá `NestedMessageObject`s, tak sa rieši priamo content `MessageObject`u, inak content `NestedMessageObject`u.

**Comment by jsuchal** [comment]
A ako bonus. Tá príloha môže byť PDF (a aj je)

**Comment by luciajanikova** [comment]
@stage-rl pri tejto ulohe je vsetko jasne, mas k tomu vsetko co potrebujes?

**Comment by luciajanikova** [comment]
> @stage-rl pri tejto ulohe je vsetko jasne, mas k tomu vsetko co potrebujes?

@stage-rl
