### ISSUE TITLE
CallbackError, keď login screen vyprší

### ISSUE THREAD

**Issue by luciajanikova** [slovensko-digital/govbox-pro#456]
Keď sa používateľ prihlási do GovBox PRO cez google účet a hneď po prihlásení spraví krok späť na prihlásenie a znova klikne na výber účtu, tak vznikne `OmniAuth::Strategies::OAuth2::CallbackError`, viď screenshot z Rollbaru. Chceme vyriešiť, aby to pre používateľa nekončilo errorom.
<img width="1147" alt="image" src="https://github.com/user-attachments/assets/a0909b03-0a60-468f-9b23-0c3e60369852">

**Comment by xHyroM** [comment]
related https://github.com/omniauth/omniauth-oauth2/issues/95

**Comment by xhyrom** [comment]
V tomto prípade bude asi jediné riešenie si forknúť omniauth oauth2 a cherry picknúť. Skúsim sa s tým pohrať a ak to bude fungovať, dohodneme ďalej.

**Comment by xhyrom** [comment]
Podarilo sa mi to vyriešiť - https://github.com/xhyrom-utils/omniauth-oauth2/commit/a6e7ede438537b3f71c81204b362a71401862386 (postupoval som tak, ako písal [gregnavis](https://github.com/gregnavis) v issue hore). Musíme si to forknúť, keďže to oficiálne repo vyzerá neudržiavane.

**Comment by luciajanikova** [comment]
@jsuchal pozries prosim?

**Comment by jsuchal** [comment]
@xhyrom @luciajanikova mam trosku averziu na forky a vseobecne chytanie security-related gemov - toto moze mat katastrofalne nasledky. 

Ja mam pocit, ze tento error sa deje aj inokedy - napriklad ked mam login screen google dlho otvoreny a potom sa snazim prihlasit (asi session vyprsi). Mne pride, ze bezpecnejsie riesenie by bolo ten exception odchytit v rails alebo niekde a spravit logout alebo nic.

**Comment by xhyrom** [comment]
Tak dá sa to aj vyriešiť odstránením histórie a teda nebudeš môcť ísť back, ale odchytiť to môžme 🤷

**Comment by jsuchal** [comment]
Ja to chapem tak, ze ani teraz back nepojde, lebo to robi redirect aj tak hned spat.
