### ISSUE TITLE
Overiť, čo sa udeje keď súčasne dvaja používatelia kliknú odoslať pri správe

### ISSUE THREAD

**Issue by luciajanikova** [slovensko-digital/govbox-pro#457]
Treba overiť ako sa bude správať súbeh kliknutia odoslať draftu, či nenastane odoslanie dvakrát.

**Comment by crutch** [comment]
Vysledok experimentu:
1. sprava sa pokusla odoslat dvakrat
2. prvy pokus presiel, druhy nie
3. fail druheho vsak prepisal uspech prveho, na oboch pocitacoch sa to javilo ako neuspesne odoslane

**Comment by trnal** [comment]
Main issue: dvakrat sa mi to pokusi poslat (prepise sa mi result)

Navrh na riesenie: 
- pridat unique key na job (aby mohol bezat pre message #1 len jeden)
- schedulovat job s message_id namiesto objektu, tym padom si ho vzdy na zaciatku jobu musime vytiahnut fresh z db a mozeme overit, ci uz nahodou nie je submitted -> toto mozno netreba, ak to uz tak na pozadi funguje?

**Comment by luciajanikova** [comment]
Vyriesene v #508.
