### ISSUE TITLE
Nerobiť retry pri SubmissionErrore

### ISSUE THREAD

**Issue by luciajanikova** [slovensko-digital/govbox-pro#492]
Tu máme nastavenia pre temporary error, vtedy retry chceme: https://github.com/slovensko-digital/govbox-pro/blob/main/app/jobs/govbox/submit_message_draft_job.rb#L8 . Ale naopak, pri terminujúcej chybe, SubmissionErrore nechceme retries. Podanie je nevalidné z nejakého dôvodu a to sa už nezmení vo fáze odosielania.

**Comment by crutch** [comment]
Na toto sa pozriem

**Comment by crutch** [comment]
Staci pridat toto do `submit_message_draft_job.rb` a joby budu rovno failovat na prvom attempte, bez retry

```ruby
retry_on SubmissionError, attempts: 1 do |_job, _error|
    # no-op
end
```

**Comment by luciajanikova** [comment]
Pozri PR @crutch https://github.com/slovensko-digital/govbox-pro/pull/507

**Comment by crutch** [comment]
Je to spravne. Neviem ci si tie submission errors chcete niekde trackovat v nejakom monitoringu alebo je ten good job dashboard vlastne monitoring (ma to alerting?)

Kazdopadne tie tri riadky tam plnia zadanie :) 👍
