### ISSUE TITLE
Blank results visualization: notifications

### ISSUE THREAD

**Issue by luciajanikova** [slovensko-digital/govbox-pro#510]
v #504 sa vyriesila blank results visualization, ale pozabudlo sa trochu na notifikacie. Tie by sme tiez chceli zahrnut.

**Comment by luciajanikova** [comment]
@stage-rl toto by mozno mohla byt fajn uloha pre Richarda, ak by si chcel este nieco v GO skusit. Podla vzorovej implementacie by sme potrebovali iba spravit to iste pre iny pripad, pre notifikacie.
Dajt/te vediet prosim.

**Comment by stage-rl** [comment]
Jasne, pozrieme, spravime

**Comment by richardlences** [comment]
https://github.com/slovensko-digital/govbox-pro/pull/512

@luciajanikova asi mozes zavriet
